# scalar Date

schema {
    query: Query
}

type Query {
    users: [User]
    user(login: String): User
}

type User {
    id: ID!
    login: String!
    firstName: String
    lastName: String
    email: String
    activated: Boolean
    langKey: String
    imageUrl: String
    createdBy: String
    createdDate: String
    lastModifiedBy: String
    lastModifiedDate: String
    authorities: [String]
}